spring:
  application:
    name: task-management-system
  data:
    mongodb:
      uri: mongodb+srv://vickyuser:kiwi%402015@vickycluster.0rvos.mongodb.net/taskdb?retryWrites=true&w=majority&appName=vickycluster
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: localhost:9092
  logging:
    level:
      org.springframework.data.redis: DEBUG
      io.lettuce.core: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    threaddump:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      redis:
        enabled: true